#############################################################################
# Makefile for building: status
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  ../RBM_status/status.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile ../RBM_status/status.pro -spec linux-g++ CONFIG+=qtquickcompiler
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_SIGNALS_SLOTS_KEYWORDS -DQT_NO_KEYWORDS -DUSE_SRV -DQT_NO_DEBUG -DQT_GAMEPAD_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -O3 -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I../RBM_status -I. -I/usr/include/opencv4 -I/usr/include/vtk-9.1 -I/usr/include/pcl-1.12 -I/usr/include/eigen3 -I/usr/local/include/sophus -I/usr/local/include -I/usr/local/include/gtsam -I/usr/local/include/octomap -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/local/include/sick_safetyscanners_base -I../../OrbbecSDK/SDK/include -I../../rplidar_sdk/sdk/include -I../RBM_status/blidar -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = status1.0.0
DISTDIR = /home/lee/code/build-status-Desktop-Release/.tmp/status1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/lib/x86_64-linux-gnu/ -lopencv_core -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc -lopencv_calib3d -lopencv_features2d -lopencv_flann -lopencv_objdetect -lopencv_photo -lopencv_video -lopencv_videoio -lopencv_ximgproc -lopencv_aruco -L/usr/local/lib/ -lvtkCommonColor-9.1 -lvtkCommonExecutionModel-9.1 -lvtkCommonCore-9.1 -lvtkCommonDataModel-9.1 -lvtkCommonMath-9.1 -lvtkFiltersCore-9.1 -lvtkFiltersSources-9.1 -lvtkFiltersGeometry-9.1 -lvtkInfovisCore-9.1 -lvtkInteractionStyle-9.1 -lvtkRenderingContextOpenGL2-9.1 -lvtkRenderingCore-9.1 -lvtkRenderingFreeType-9.1 -lvtkRenderingGL2PSOpenGL2-9.1 -lvtkRenderingOpenGL2-9.1 -lvtkViewsQt-9.1 -lvtkGUISupportQt-9.1 -lvtkRenderingQt-9.1 -lvtkRenderingLOD-9.1 -ljsoncpp -L/usr/lib/aarch64-linux-gnu/ -lpcl_common -lpcl_features -lpcl_filters -lpcl_io -lpcl_io_ply -lpcl_kdtree -lpcl_keypoints -lpcl_ml -lpcl_octree -lpcl_outofcore -lpcl_people -lpcl_recognition -lpcl_registration -lpcl_sample_consensus -lpcl_search -lpcl_segmentation -lpcl_stereo -lpcl_surface -lpcl_tracking -lpcl_visualization -ltbb -lsioclient -lsioclient_tls -lgtsam -lmetis-gtsam -loctomath -loctomap -lboost_system -lboost_thread -lsick_safetyscanners_base -L/home/lee/OrbbecSDK/SDK/lib/ -lOrbbecSDK -L/home/lee/rplidar_sdk/output/Linux/Release/ -lsl_lidar_sdk /usr/lib/x86_64-linux-gnu/libQt5Gamepad.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5WebSockets.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5SerialPort.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../RBM_status/main.cpp \
		../RBM_status/mainwindow.cpp \
		../RBM_status/cam.cpp \
		../RBM_status/mobile.cpp \
		../RBM_status/cv_to_qt.cpp \
		../RBM_status/my_utils.cpp \
		../RBM_status/config.cpp \
		../RBM_status/LakiBeamHTTP.cpp \
		../RBM_status/LakiBeamUDP.cpp \
		../RBM_status/lidar_2d.cpp \
		../RBM_status/lidar_bottom.cpp \
		../RBM_status/logger.cpp \
		../RBM_status/code_reader.cpp \
		../RBM_status/blidar/calibration.cpp \
		../RBM_status/blidar/lidar_data_processing.cpp \
		../RBM_status/blidar/lidar_information.cpp \
		../RBM_status/blidar/mtime.cpp \
		../RBM_status/blidar/node_lidar.cpp \
		../RBM_status/blidar/point_cloud_optimize.cpp \
		../RBM_status/blidar/serial_port.cpp \
		../RBM_status/blidar/timer.cpp moc_mainwindow.cpp \
		moc_cam.cpp \
		moc_mobile.cpp \
		moc_config.cpp \
		moc_lidar_2d.cpp \
		moc_lidar_bottom.cpp \
		moc_logger.cpp \
		moc_code_reader.cpp
OBJECTS       = main.o \
		mainwindow.o \
		cam.o \
		mobile.o \
		cv_to_qt.o \
		my_utils.o \
		config.o \
		LakiBeamHTTP.o \
		LakiBeamUDP.o \
		lidar_2d.o \
		lidar_bottom.o \
		logger.o \
		code_reader.o \
		calibration.o \
		lidar_data_processing.o \
		lidar_information.o \
		mtime.o \
		node_lidar.o \
		point_cloud_optimize.o \
		serial_port.o \
		timer.o \
		moc_mainwindow.o \
		moc_cam.o \
		moc_mobile.o \
		moc_config.o \
		moc_lidar_2d.o \
		moc_lidar_bottom.o \
		moc_logger.o \
		moc_code_reader.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		../RBM_status/.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qtquickcompiler.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		../RBM_status/status.pro ../RBM_status/mainwindow.h \
		../RBM_status/cam.h \
		../RBM_status/global_defines.h \
		../RBM_status/mobile.h \
		../RBM_status/cv_to_qt.h \
		../RBM_status/nanoflann.hpp \
		../RBM_status/tinycolormap.hpp \
		../RBM_status/my_utils.h \
		../RBM_status/config.h \
		../RBM_status/LakiBeamHTTP.h \
		../RBM_status/LakiBeamUDP.h \
		../RBM_status/lidar_2d.h \
		../RBM_status/lidar_bottom.h \
		../RBM_status/logger.h \
		../RBM_status/code_reader.h \
		../RBM_status/blidar/calibration.h \
		../RBM_status/blidar/lidar_data_processing.h \
		../RBM_status/blidar/lidar_information.h \
		../RBM_status/blidar/locker.h \
		../RBM_status/blidar/msg_recept.h \
		../RBM_status/blidar/mtime.h \
		../RBM_status/blidar/node_lidar.h \
		../RBM_status/blidar/point_cloud_optimize.h \
		../RBM_status/blidar/serial_port.h \
		../RBM_status/blidar/timer.h ../RBM_status/main.cpp \
		../RBM_status/mainwindow.cpp \
		../RBM_status/cam.cpp \
		../RBM_status/mobile.cpp \
		../RBM_status/cv_to_qt.cpp \
		../RBM_status/my_utils.cpp \
		../RBM_status/config.cpp \
		../RBM_status/LakiBeamHTTP.cpp \
		../RBM_status/LakiBeamUDP.cpp \
		../RBM_status/lidar_2d.cpp \
		../RBM_status/lidar_bottom.cpp \
		../RBM_status/logger.cpp \
		../RBM_status/code_reader.cpp \
		../RBM_status/blidar/calibration.cpp \
		../RBM_status/blidar/lidar_data_processing.cpp \
		../RBM_status/blidar/lidar_information.cpp \
		../RBM_status/blidar/mtime.cpp \
		../RBM_status/blidar/node_lidar.cpp \
		../RBM_status/blidar/point_cloud_optimize.cpp \
		../RBM_status/blidar/serial_port.cpp \
		../RBM_status/blidar/timer.cpp
QMAKE_TARGET  = status
DESTDIR       = 
TARGET        = status


first: all
####### Build rules

status: ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../RBM_status/status.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qtquickcompiler.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		../RBM_status/status.pro
	$(QMAKE) -o Makefile ../RBM_status/status.pro -spec linux-g++ CONFIG+=qtquickcompiler
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gamepad.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qtquickcompiler.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
../RBM_status/status.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile ../RBM_status/status.pro -spec linux-g++ CONFIG+=qtquickcompiler

qmake_all: FORCE


all: Makefile status

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../RBM_status/mainwindow.h ../RBM_status/cam.h ../RBM_status/global_defines.h ../RBM_status/mobile.h ../RBM_status/cv_to_qt.h ../RBM_status/nanoflann.hpp ../RBM_status/tinycolormap.hpp ../RBM_status/my_utils.h ../RBM_status/config.h ../RBM_status/LakiBeamHTTP.h ../RBM_status/LakiBeamUDP.h ../RBM_status/lidar_2d.h ../RBM_status/lidar_bottom.h ../RBM_status/logger.h ../RBM_status/code_reader.h ../RBM_status/blidar/calibration.h ../RBM_status/blidar/lidar_data_processing.h ../RBM_status/blidar/lidar_information.h ../RBM_status/blidar/locker.h ../RBM_status/blidar/msg_recept.h ../RBM_status/blidar/mtime.h ../RBM_status/blidar/node_lidar.h ../RBM_status/blidar/point_cloud_optimize.h ../RBM_status/blidar/serial_port.h ../RBM_status/blidar/timer.h $(DISTDIR)/
	$(COPY_FILE) --parents ../RBM_status/main.cpp ../RBM_status/mainwindow.cpp ../RBM_status/cam.cpp ../RBM_status/mobile.cpp ../RBM_status/cv_to_qt.cpp ../RBM_status/my_utils.cpp ../RBM_status/config.cpp ../RBM_status/LakiBeamHTTP.cpp ../RBM_status/LakiBeamUDP.cpp ../RBM_status/lidar_2d.cpp ../RBM_status/lidar_bottom.cpp ../RBM_status/logger.cpp ../RBM_status/code_reader.cpp ../RBM_status/blidar/calibration.cpp ../RBM_status/blidar/lidar_data_processing.cpp ../RBM_status/blidar/lidar_information.cpp ../RBM_status/blidar/mtime.cpp ../RBM_status/blidar/node_lidar.cpp ../RBM_status/blidar/point_cloud_optimize.cpp ../RBM_status/blidar/serial_port.cpp ../RBM_status/blidar/timer.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../RBM_status/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -O3 -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_cam.cpp moc_mobile.cpp moc_config.cpp moc_lidar_2d.cpp moc_lidar_bottom.cpp moc_logger.cpp moc_code_reader.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_cam.cpp moc_mobile.cpp moc_config.cpp moc_lidar_2d.cpp moc_lidar_bottom.cpp moc_logger.cpp moc_code_reader.cpp
moc_mainwindow.cpp: ../RBM_status/mainwindow.h \
		../RBM_status/global_defines.h \
		../RBM_status/cv_to_qt.h \
		../RBM_status/nanoflann.hpp \
		../RBM_status/tinycolormap.hpp \
		../RBM_status/node_lidar.h \
		../RBM_status/point_cloud_optimize.h \
		../RBM_status/lidar_data_processing.h \
		../RBM_status/lidar_information.h \
		../RBM_status/serial_port.h \
		../RBM_status/locker.h \
		../RBM_status/timer.h \
		../RBM_status/my_utils.h \
		../RBM_status/config.h \
		../RBM_status/logger.h \
		../RBM_status/mobile.h \
		../RBM_status/lidar_2d.h \
		../../rplidar_sdk/sdk/include/sl_lidar.h \
		../../rplidar_sdk/sdk/include/sl_lidar_driver.h \
		../../rplidar_sdk/sdk/include/sl_lidar_cmd.h \
		../../rplidar_sdk/sdk/include/sl_lidar_protocol.h \
		../../rplidar_sdk/sdk/include/sl_types.h \
		../RBM_status/LakiBeamHTTP.h \
		../RBM_status/LakiBeamUDP.h \
		../RBM_status/lidar_bottom.h \
		../RBM_status/blidar/msg_recept.h \
		../RBM_status/blidar/mtime.h \
		../RBM_status/blidar/calibration.h \
		../RBM_status/blidar/lidar_information.h \
		../RBM_status/cam.h \
		../../OrbbecSDK/SDK/include/libobsensor/ObSensor.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Context.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Types.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/h/ObTypes.h \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Device.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/h/Property.h \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Filter.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Error.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Frame.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Pipeline.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/RecordPlayback.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Sensor.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/StreamProfile.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Version.hpp \
		../RBM_status/code_reader.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/lee/code/build-status-Desktop-Release/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/lee/code/RBM_status -I/usr/include/opencv4 -I/usr/include/vtk-9.1 -I/usr/include/pcl-1.12 -I/usr/include/eigen3 -I/usr/local/include/sophus -I/usr/local/include -I/usr/local/include/gtsam -I/usr/local/include/octomap -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/local/include/sick_safetyscanners_base -I/home/lee/OrbbecSDK/SDK/include -I/home/lee/rplidar_sdk/sdk/include -I/home/lee/code/RBM_status/blidar -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ../RBM_status/mainwindow.h -o moc_mainwindow.cpp

moc_cam.cpp: ../RBM_status/cam.h \
		../RBM_status/global_defines.h \
		../RBM_status/cv_to_qt.h \
		../RBM_status/nanoflann.hpp \
		../RBM_status/tinycolormap.hpp \
		../RBM_status/node_lidar.h \
		../RBM_status/point_cloud_optimize.h \
		../RBM_status/lidar_data_processing.h \
		../RBM_status/lidar_information.h \
		../RBM_status/serial_port.h \
		../RBM_status/locker.h \
		../RBM_status/timer.h \
		../RBM_status/my_utils.h \
		../RBM_status/config.h \
		../RBM_status/logger.h \
		../RBM_status/mobile.h \
		../../OrbbecSDK/SDK/include/libobsensor/ObSensor.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Context.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Types.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/h/ObTypes.h \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Device.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/h/Property.h \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Filter.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Error.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Frame.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Pipeline.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/RecordPlayback.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Sensor.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/StreamProfile.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Version.hpp \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/lee/code/build-status-Desktop-Release/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/lee/code/RBM_status -I/usr/include/opencv4 -I/usr/include/vtk-9.1 -I/usr/include/pcl-1.12 -I/usr/include/eigen3 -I/usr/local/include/sophus -I/usr/local/include -I/usr/local/include/gtsam -I/usr/local/include/octomap -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/local/include/sick_safetyscanners_base -I/home/lee/OrbbecSDK/SDK/include -I/home/lee/rplidar_sdk/sdk/include -I/home/lee/code/RBM_status/blidar -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ../RBM_status/cam.h -o moc_cam.cpp

moc_mobile.cpp: ../RBM_status/mobile.h \
		../RBM_status/global_defines.h \
		../RBM_status/cv_to_qt.h \
		../RBM_status/nanoflann.hpp \
		../RBM_status/tinycolormap.hpp \
		../RBM_status/node_lidar.h \
		../RBM_status/point_cloud_optimize.h \
		../RBM_status/lidar_data_processing.h \
		../RBM_status/lidar_information.h \
		../RBM_status/serial_port.h \
		../RBM_status/locker.h \
		../RBM_status/timer.h \
		../RBM_status/my_utils.h \
		../RBM_status/config.h \
		../RBM_status/logger.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/lee/code/build-status-Desktop-Release/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/lee/code/RBM_status -I/usr/include/opencv4 -I/usr/include/vtk-9.1 -I/usr/include/pcl-1.12 -I/usr/include/eigen3 -I/usr/local/include/sophus -I/usr/local/include -I/usr/local/include/gtsam -I/usr/local/include/octomap -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/local/include/sick_safetyscanners_base -I/home/lee/OrbbecSDK/SDK/include -I/home/lee/rplidar_sdk/sdk/include -I/home/lee/code/RBM_status/blidar -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ../RBM_status/mobile.h -o moc_mobile.cpp

moc_config.cpp: ../RBM_status/config.h \
		../RBM_status/global_defines.h \
		../RBM_status/cv_to_qt.h \
		../RBM_status/nanoflann.hpp \
		../RBM_status/tinycolormap.hpp \
		../RBM_status/node_lidar.h \
		../RBM_status/point_cloud_optimize.h \
		../RBM_status/lidar_data_processing.h \
		../RBM_status/lidar_information.h \
		../RBM_status/serial_port.h \
		../RBM_status/locker.h \
		../RBM_status/timer.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/lee/code/build-status-Desktop-Release/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/lee/code/RBM_status -I/usr/include/opencv4 -I/usr/include/vtk-9.1 -I/usr/include/pcl-1.12 -I/usr/include/eigen3 -I/usr/local/include/sophus -I/usr/local/include -I/usr/local/include/gtsam -I/usr/local/include/octomap -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/local/include/sick_safetyscanners_base -I/home/lee/OrbbecSDK/SDK/include -I/home/lee/rplidar_sdk/sdk/include -I/home/lee/code/RBM_status/blidar -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ../RBM_status/config.h -o moc_config.cpp

moc_lidar_2d.cpp: ../RBM_status/lidar_2d.h \
		../RBM_status/global_defines.h \
		../RBM_status/cv_to_qt.h \
		../RBM_status/nanoflann.hpp \
		../RBM_status/tinycolormap.hpp \
		../RBM_status/node_lidar.h \
		../RBM_status/point_cloud_optimize.h \
		../RBM_status/lidar_data_processing.h \
		../RBM_status/lidar_information.h \
		../RBM_status/serial_port.h \
		../RBM_status/locker.h \
		../RBM_status/timer.h \
		../RBM_status/my_utils.h \
		../../rplidar_sdk/sdk/include/sl_lidar.h \
		../../rplidar_sdk/sdk/include/sl_lidar_driver.h \
		../../rplidar_sdk/sdk/include/sl_lidar_cmd.h \
		../../rplidar_sdk/sdk/include/sl_lidar_protocol.h \
		../../rplidar_sdk/sdk/include/sl_types.h \
		../RBM_status/LakiBeamHTTP.h \
		../RBM_status/LakiBeamUDP.h \
		../RBM_status/config.h \
		../RBM_status/logger.h \
		../RBM_status/mobile.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/lee/code/build-status-Desktop-Release/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/lee/code/RBM_status -I/usr/include/opencv4 -I/usr/include/vtk-9.1 -I/usr/include/pcl-1.12 -I/usr/include/eigen3 -I/usr/local/include/sophus -I/usr/local/include -I/usr/local/include/gtsam -I/usr/local/include/octomap -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/local/include/sick_safetyscanners_base -I/home/lee/OrbbecSDK/SDK/include -I/home/lee/rplidar_sdk/sdk/include -I/home/lee/code/RBM_status/blidar -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ../RBM_status/lidar_2d.h -o moc_lidar_2d.cpp

moc_lidar_bottom.cpp: ../RBM_status/lidar_bottom.h \
		../RBM_status/global_defines.h \
		../RBM_status/cv_to_qt.h \
		../RBM_status/nanoflann.hpp \
		../RBM_status/tinycolormap.hpp \
		../RBM_status/node_lidar.h \
		../RBM_status/point_cloud_optimize.h \
		../RBM_status/lidar_data_processing.h \
		../RBM_status/lidar_information.h \
		../RBM_status/serial_port.h \
		../RBM_status/locker.h \
		../RBM_status/timer.h \
		../RBM_status/blidar/msg_recept.h \
		../RBM_status/blidar/mtime.h \
		../RBM_status/blidar/calibration.h \
		../RBM_status/blidar/lidar_information.h \
		../RBM_status/config.h \
		../RBM_status/logger.h \
		../RBM_status/mobile.h \
		../RBM_status/my_utils.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/lee/code/build-status-Desktop-Release/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/lee/code/RBM_status -I/usr/include/opencv4 -I/usr/include/vtk-9.1 -I/usr/include/pcl-1.12 -I/usr/include/eigen3 -I/usr/local/include/sophus -I/usr/local/include -I/usr/local/include/gtsam -I/usr/local/include/octomap -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/local/include/sick_safetyscanners_base -I/home/lee/OrbbecSDK/SDK/include -I/home/lee/rplidar_sdk/sdk/include -I/home/lee/code/RBM_status/blidar -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ../RBM_status/lidar_bottom.h -o moc_lidar_bottom.cpp

moc_logger.cpp: ../RBM_status/logger.h \
		../RBM_status/global_defines.h \
		../RBM_status/cv_to_qt.h \
		../RBM_status/nanoflann.hpp \
		../RBM_status/tinycolormap.hpp \
		../RBM_status/node_lidar.h \
		../RBM_status/point_cloud_optimize.h \
		../RBM_status/lidar_data_processing.h \
		../RBM_status/lidar_information.h \
		../RBM_status/serial_port.h \
		../RBM_status/locker.h \
		../RBM_status/timer.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/lee/code/build-status-Desktop-Release/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/lee/code/RBM_status -I/usr/include/opencv4 -I/usr/include/vtk-9.1 -I/usr/include/pcl-1.12 -I/usr/include/eigen3 -I/usr/local/include/sophus -I/usr/local/include -I/usr/local/include/gtsam -I/usr/local/include/octomap -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/local/include/sick_safetyscanners_base -I/home/lee/OrbbecSDK/SDK/include -I/home/lee/rplidar_sdk/sdk/include -I/home/lee/code/RBM_status/blidar -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ../RBM_status/logger.h -o moc_logger.cpp

moc_code_reader.cpp: ../RBM_status/code_reader.h \
		../RBM_status/global_defines.h \
		../RBM_status/cv_to_qt.h \
		../RBM_status/nanoflann.hpp \
		../RBM_status/tinycolormap.hpp \
		../RBM_status/node_lidar.h \
		../RBM_status/point_cloud_optimize.h \
		../RBM_status/lidar_data_processing.h \
		../RBM_status/lidar_information.h \
		../RBM_status/serial_port.h \
		../RBM_status/locker.h \
		../RBM_status/timer.h \
		../RBM_status/config.h \
		../RBM_status/logger.h \
		../RBM_status/my_utils.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/lee/code/build-status-Desktop-Release/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/lee/code/RBM_status -I/usr/include/opencv4 -I/usr/include/vtk-9.1 -I/usr/include/pcl-1.12 -I/usr/include/eigen3 -I/usr/local/include/sophus -I/usr/local/include -I/usr/local/include/gtsam -I/usr/local/include/octomap -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/local/include/sick_safetyscanners_base -I/home/lee/OrbbecSDK/SDK/include -I/home/lee/rplidar_sdk/sdk/include -I/home/lee/code/RBM_status/blidar -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGamepad -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ../RBM_status/code_reader.h -o moc_code_reader.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: ../RBM_status/mainwindow.ui \
		/usr/lib/qt5/bin/uic \
		/usr/include/vtk-9.1/QVTKOpenGLNativeWidget.h
	/usr/lib/qt5/bin/uic ../RBM_status/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: ../RBM_status/main.cpp ../RBM_status/mainwindow.h \
		../RBM_status/global_defines.h \
		../RBM_status/cv_to_qt.h \
		../RBM_status/nanoflann.hpp \
		../RBM_status/tinycolormap.hpp \
		../RBM_status/node_lidar.h \
		../RBM_status/point_cloud_optimize.h \
		../RBM_status/lidar_data_processing.h \
		../RBM_status/lidar_information.h \
		../RBM_status/serial_port.h \
		../RBM_status/locker.h \
		../RBM_status/timer.h \
		../RBM_status/my_utils.h \
		../RBM_status/config.h \
		../RBM_status/logger.h \
		../RBM_status/mobile.h \
		../RBM_status/lidar_2d.h \
		../../rplidar_sdk/sdk/include/sl_lidar.h \
		../../rplidar_sdk/sdk/include/sl_lidar_driver.h \
		../../rplidar_sdk/sdk/include/sl_lidar_cmd.h \
		../../rplidar_sdk/sdk/include/sl_lidar_protocol.h \
		../../rplidar_sdk/sdk/include/sl_types.h \
		../RBM_status/LakiBeamHTTP.h \
		../RBM_status/LakiBeamUDP.h \
		../RBM_status/lidar_bottom.h \
		../RBM_status/blidar/msg_recept.h \
		../RBM_status/blidar/mtime.h \
		../RBM_status/blidar/calibration.h \
		../RBM_status/blidar/lidar_information.h \
		../RBM_status/cam.h \
		../../OrbbecSDK/SDK/include/libobsensor/ObSensor.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Context.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Types.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/h/ObTypes.h \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Device.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/h/Property.h \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Filter.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Error.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Frame.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Pipeline.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/RecordPlayback.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Sensor.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/StreamProfile.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Version.hpp \
		../RBM_status/code_reader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../RBM_status/main.cpp

mainwindow.o: ../RBM_status/mainwindow.cpp ../RBM_status/mainwindow.h \
		../RBM_status/global_defines.h \
		../RBM_status/cv_to_qt.h \
		../RBM_status/nanoflann.hpp \
		../RBM_status/tinycolormap.hpp \
		../RBM_status/node_lidar.h \
		../RBM_status/point_cloud_optimize.h \
		../RBM_status/lidar_data_processing.h \
		../RBM_status/lidar_information.h \
		../RBM_status/serial_port.h \
		../RBM_status/locker.h \
		../RBM_status/timer.h \
		../RBM_status/my_utils.h \
		../RBM_status/config.h \
		../RBM_status/logger.h \
		../RBM_status/mobile.h \
		../RBM_status/lidar_2d.h \
		../../rplidar_sdk/sdk/include/sl_lidar.h \
		../../rplidar_sdk/sdk/include/sl_lidar_driver.h \
		../../rplidar_sdk/sdk/include/sl_lidar_cmd.h \
		../../rplidar_sdk/sdk/include/sl_lidar_protocol.h \
		../../rplidar_sdk/sdk/include/sl_types.h \
		../RBM_status/LakiBeamHTTP.h \
		../RBM_status/LakiBeamUDP.h \
		../RBM_status/lidar_bottom.h \
		../RBM_status/blidar/msg_recept.h \
		../RBM_status/blidar/mtime.h \
		../RBM_status/blidar/calibration.h \
		../RBM_status/blidar/lidar_information.h \
		../RBM_status/cam.h \
		../../OrbbecSDK/SDK/include/libobsensor/ObSensor.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Context.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Types.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/h/ObTypes.h \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Device.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/h/Property.h \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Filter.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Error.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Frame.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Pipeline.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/RecordPlayback.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Sensor.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/StreamProfile.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Version.hpp \
		../RBM_status/code_reader.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../RBM_status/mainwindow.cpp

cam.o: ../RBM_status/cam.cpp ../RBM_status/cam.h \
		../RBM_status/global_defines.h \
		../RBM_status/cv_to_qt.h \
		../RBM_status/nanoflann.hpp \
		../RBM_status/tinycolormap.hpp \
		../RBM_status/node_lidar.h \
		../RBM_status/point_cloud_optimize.h \
		../RBM_status/lidar_data_processing.h \
		../RBM_status/lidar_information.h \
		../RBM_status/serial_port.h \
		../RBM_status/locker.h \
		../RBM_status/timer.h \
		../RBM_status/my_utils.h \
		../RBM_status/config.h \
		../RBM_status/logger.h \
		../RBM_status/mobile.h \
		../../OrbbecSDK/SDK/include/libobsensor/ObSensor.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Context.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Types.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/h/ObTypes.h \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Device.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/h/Property.h \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Filter.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Error.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Frame.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Pipeline.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/RecordPlayback.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Sensor.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/StreamProfile.hpp \
		../../OrbbecSDK/SDK/include/libobsensor/hpp/Version.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cam.o ../RBM_status/cam.cpp

mobile.o: ../RBM_status/mobile.cpp ../RBM_status/mobile.h \
		../RBM_status/global_defines.h \
		../RBM_status/cv_to_qt.h \
		../RBM_status/nanoflann.hpp \
		../RBM_status/tinycolormap.hpp \
		../RBM_status/node_lidar.h \
		../RBM_status/point_cloud_optimize.h \
		../RBM_status/lidar_data_processing.h \
		../RBM_status/lidar_information.h \
		../RBM_status/serial_port.h \
		../RBM_status/locker.h \
		../RBM_status/timer.h \
		../RBM_status/my_utils.h \
		../RBM_status/config.h \
		../RBM_status/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mobile.o ../RBM_status/mobile.cpp

cv_to_qt.o: ../RBM_status/cv_to_qt.cpp ../RBM_status/cv_to_qt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cv_to_qt.o ../RBM_status/cv_to_qt.cpp

my_utils.o: ../RBM_status/my_utils.cpp ../RBM_status/my_utils.h \
		../RBM_status/global_defines.h \
		../RBM_status/cv_to_qt.h \
		../RBM_status/nanoflann.hpp \
		../RBM_status/tinycolormap.hpp \
		../RBM_status/node_lidar.h \
		../RBM_status/point_cloud_optimize.h \
		../RBM_status/lidar_data_processing.h \
		../RBM_status/lidar_information.h \
		../RBM_status/serial_port.h \
		../RBM_status/locker.h \
		../RBM_status/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o my_utils.o ../RBM_status/my_utils.cpp

config.o: ../RBM_status/config.cpp ../RBM_status/config.h \
		../RBM_status/global_defines.h \
		../RBM_status/cv_to_qt.h \
		../RBM_status/nanoflann.hpp \
		../RBM_status/tinycolormap.hpp \
		../RBM_status/node_lidar.h \
		../RBM_status/point_cloud_optimize.h \
		../RBM_status/lidar_data_processing.h \
		../RBM_status/lidar_information.h \
		../RBM_status/serial_port.h \
		../RBM_status/locker.h \
		../RBM_status/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o config.o ../RBM_status/config.cpp

LakiBeamHTTP.o: ../RBM_status/LakiBeamHTTP.cpp ../RBM_status/LakiBeamHTTP.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LakiBeamHTTP.o ../RBM_status/LakiBeamHTTP.cpp

LakiBeamUDP.o: ../RBM_status/LakiBeamUDP.cpp ../RBM_status/LakiBeamUDP.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LakiBeamUDP.o ../RBM_status/LakiBeamUDP.cpp

lidar_2d.o: ../RBM_status/lidar_2d.cpp ../RBM_status/lidar_2d.h \
		../RBM_status/global_defines.h \
		../RBM_status/cv_to_qt.h \
		../RBM_status/nanoflann.hpp \
		../RBM_status/tinycolormap.hpp \
		../RBM_status/node_lidar.h \
		../RBM_status/point_cloud_optimize.h \
		../RBM_status/lidar_data_processing.h \
		../RBM_status/lidar_information.h \
		../RBM_status/serial_port.h \
		../RBM_status/locker.h \
		../RBM_status/timer.h \
		../RBM_status/my_utils.h \
		../../rplidar_sdk/sdk/include/sl_lidar.h \
		../../rplidar_sdk/sdk/include/sl_lidar_driver.h \
		../../rplidar_sdk/sdk/include/sl_lidar_cmd.h \
		../../rplidar_sdk/sdk/include/sl_lidar_protocol.h \
		../../rplidar_sdk/sdk/include/sl_types.h \
		../RBM_status/LakiBeamHTTP.h \
		../RBM_status/LakiBeamUDP.h \
		../RBM_status/config.h \
		../RBM_status/logger.h \
		../RBM_status/mobile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lidar_2d.o ../RBM_status/lidar_2d.cpp

lidar_bottom.o: ../RBM_status/lidar_bottom.cpp ../RBM_status/lidar_bottom.h \
		../RBM_status/global_defines.h \
		../RBM_status/cv_to_qt.h \
		../RBM_status/nanoflann.hpp \
		../RBM_status/tinycolormap.hpp \
		../RBM_status/node_lidar.h \
		../RBM_status/point_cloud_optimize.h \
		../RBM_status/lidar_data_processing.h \
		../RBM_status/lidar_information.h \
		../RBM_status/serial_port.h \
		../RBM_status/locker.h \
		../RBM_status/timer.h \
		../RBM_status/blidar/msg_recept.h \
		../RBM_status/blidar/mtime.h \
		../RBM_status/blidar/calibration.h \
		../RBM_status/blidar/lidar_information.h \
		../RBM_status/config.h \
		../RBM_status/logger.h \
		../RBM_status/mobile.h \
		../RBM_status/my_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lidar_bottom.o ../RBM_status/lidar_bottom.cpp

logger.o: ../RBM_status/logger.cpp ../RBM_status/logger.h \
		../RBM_status/global_defines.h \
		../RBM_status/cv_to_qt.h \
		../RBM_status/nanoflann.hpp \
		../RBM_status/tinycolormap.hpp \
		../RBM_status/node_lidar.h \
		../RBM_status/point_cloud_optimize.h \
		../RBM_status/lidar_data_processing.h \
		../RBM_status/lidar_information.h \
		../RBM_status/serial_port.h \
		../RBM_status/locker.h \
		../RBM_status/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logger.o ../RBM_status/logger.cpp

code_reader.o: ../RBM_status/code_reader.cpp ../RBM_status/code_reader.h \
		../RBM_status/global_defines.h \
		../RBM_status/cv_to_qt.h \
		../RBM_status/nanoflann.hpp \
		../RBM_status/tinycolormap.hpp \
		../RBM_status/node_lidar.h \
		../RBM_status/point_cloud_optimize.h \
		../RBM_status/lidar_data_processing.h \
		../RBM_status/lidar_information.h \
		../RBM_status/serial_port.h \
		../RBM_status/locker.h \
		../RBM_status/timer.h \
		../RBM_status/config.h \
		../RBM_status/logger.h \
		../RBM_status/my_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o code_reader.o ../RBM_status/code_reader.cpp

calibration.o: ../RBM_status/blidar/calibration.cpp ../RBM_status/blidar/calibration.h \
		../RBM_status/blidar/lidar_information.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calibration.o ../RBM_status/blidar/calibration.cpp

lidar_data_processing.o: ../RBM_status/blidar/lidar_data_processing.cpp ../RBM_status/blidar/msg_recept.h \
		../RBM_status/blidar/serial_port.h \
		../RBM_status/blidar/lidar_information.h \
		../RBM_status/blidar/lidar_data_processing.h \
		../RBM_status/blidar/mtime.h \
		../RBM_status/blidar/node_lidar.h \
		../RBM_status/blidar/point_cloud_optimize.h \
		../RBM_status/blidar/locker.h \
		../RBM_status/blidar/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lidar_data_processing.o ../RBM_status/blidar/lidar_data_processing.cpp

lidar_information.o: ../RBM_status/blidar/lidar_information.cpp ../RBM_status/blidar/node_lidar.h \
		../RBM_status/blidar/point_cloud_optimize.h \
		../RBM_status/blidar/lidar_data_processing.h \
		../RBM_status/blidar/lidar_information.h \
		../RBM_status/blidar/serial_port.h \
		../RBM_status/blidar/locker.h \
		../RBM_status/blidar/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lidar_information.o ../RBM_status/blidar/lidar_information.cpp

mtime.o: ../RBM_status/blidar/mtime.cpp ../RBM_status/blidar/mtime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mtime.o ../RBM_status/blidar/mtime.cpp

node_lidar.o: ../RBM_status/blidar/node_lidar.cpp ../RBM_status/blidar/node_lidar.h \
		../RBM_status/blidar/point_cloud_optimize.h \
		../RBM_status/blidar/lidar_data_processing.h \
		../RBM_status/blidar/lidar_information.h \
		../RBM_status/blidar/serial_port.h \
		../RBM_status/blidar/locker.h \
		../RBM_status/blidar/timer.h \
		../RBM_status/blidar/msg_recept.h \
		../RBM_status/blidar/mtime.h \
		../RBM_status/blidar/calibration.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o node_lidar.o ../RBM_status/blidar/node_lidar.cpp

point_cloud_optimize.o: ../RBM_status/blidar/point_cloud_optimize.cpp ../RBM_status/blidar/node_lidar.h \
		../RBM_status/blidar/point_cloud_optimize.h \
		../RBM_status/blidar/lidar_data_processing.h \
		../RBM_status/blidar/lidar_information.h \
		../RBM_status/blidar/serial_port.h \
		../RBM_status/blidar/locker.h \
		../RBM_status/blidar/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o point_cloud_optimize.o ../RBM_status/blidar/point_cloud_optimize.cpp

serial_port.o: ../RBM_status/blidar/serial_port.cpp ../RBM_status/blidar/serial_port.h \
		../RBM_status/blidar/lidar_information.h \
		../RBM_status/blidar/node_lidar.h \
		../RBM_status/blidar/point_cloud_optimize.h \
		../RBM_status/blidar/lidar_data_processing.h \
		../RBM_status/blidar/locker.h \
		../RBM_status/blidar/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serial_port.o ../RBM_status/blidar/serial_port.cpp

timer.o: ../RBM_status/blidar/timer.cpp ../RBM_status/blidar/timer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timer.o ../RBM_status/blidar/timer.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_cam.o: moc_cam.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cam.o moc_cam.cpp

moc_mobile.o: moc_mobile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mobile.o moc_mobile.cpp

moc_config.o: moc_config.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_config.o moc_config.cpp

moc_lidar_2d.o: moc_lidar_2d.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lidar_2d.o moc_lidar_2d.cpp

moc_lidar_bottom.o: moc_lidar_bottom.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lidar_bottom.o moc_lidar_bottom.cpp

moc_logger.o: moc_logger.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_logger.o moc_logger.cpp

moc_code_reader.o: moc_code_reader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_code_reader.o moc_code_reader.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/status/bin || mkdir -p $(INSTALL_ROOT)/opt/status/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/status/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/status/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/status/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/status/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

